# Generated by Django 5.0.6 on 2024-06-12 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Answer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "answer_text",
                    models.CharField(max_length=255, verbose_name="текст ответа"),
                ),
            ],
            options={
                "verbose_name": "текст ответа",
                "verbose_name_plural": "тексты ответов",
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="загаловок")),
            ],
            options={
                "verbose_name": "категория ",
                "verbose_name_plural": "категории",
            },
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "question_text",
                    models.CharField(max_length=255, verbose_name="текст вопроса"),
                ),
                (
                    "answer",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="correct_answer",
                        to="quiz.answer",
                        verbose_name="правильный ответ",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="quiz.category",
                        verbose_name="категория",
                    ),
                ),
                (
                    "choices",
                    models.ManyToManyField(
                        related_name="choices",
                        to="quiz.answer",
                        verbose_name="выбор ответа",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Quiz",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quiz_title",
                    models.CharField(max_length=255, verbose_name="заголовок теста"),
                ),
                (
                    "category",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="quiz.category",
                        verbose_name="категория",
                    ),
                ),
                (
                    "question",
                    models.ManyToManyField(
                        blank=True, to="quiz.question", verbose_name="вопрос"
                    ),
                ),
            ],
            options={
                "verbose_name": "тест",
                "verbose_name_plural": "тесты",
            },
        ),
    ]
