# Generated by Django 5.0.6 on 2024-06-12 20:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="answer",
            options={"verbose_name": "ответ", "verbose_name_plural": "ответы"},
        ),
        migrations.AlterModelOptions(
            name="question",
            options={"verbose_name": "вопрос", "verbose_name_plural": "вопросы"},
        ),
        migrations.AlterModelOptions(
            name="quiz",
            options={"verbose_name": "тест", "verbose_name_plural": "тесты"},
        ),
        migrations.AlterField(
            model_name="answer",
            name="is_correct",
            field=models.BooleanField(
                default=False, verbose_name="правильность ответа"
            ),
        ),
        migrations.AlterField(
            model_name="answer",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="quiz.question",
                verbose_name="вопрос",
            ),
        ),
        migrations.AlterField(
            model_name="answer",
            name="text",
            field=models.CharField(max_length=300, verbose_name="текст ответа"),
        ),
        migrations.AlterField(
            model_name="question",
            name="quiz",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="quiz.quiz",
                verbose_name="название теста",
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="text",
            field=models.CharField(max_length=300, verbose_name="текст вопроса"),
        ),
        migrations.AlterField(
            model_name="quiz",
            name="name",
            field=models.CharField(max_length=300, verbose_name="Название теста"),
        ),
    ]
