# Generated by Django 5.0.6 on 2024-06-13 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0001_initial"),
        ("quiz", "0002_alter_answer_options_alter_question_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="material",
            name="quiz",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="quiz",
                to="quiz.quiz",
                verbose_name="тестовый материал",
            ),
        ),
    ]
