# Generated by Django 5.0.6 on 2024-06-13 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0002_material_quiz"),
    ]

    operations = [
        migrations.AlterField(
            model_name="material",
            name="section",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="material",
                to="courses.section",
                verbose_name="раздел",
            ),
        ),
    ]
